ProcessThreadManager: PTManager::ProcessManager Class Reference
PTManager::ProcessManager Class Reference
#include <ProcessManager.h>
Public Member Functions
ProcessManager ()=default
~ProcessManager ()
Destructor that ensures all managed processes are cleaned up.
pid_t createProcess (const std::string &name, std::function< int()> task)
Creates a new child process to execute a task.
bool waitForProcess (pid_t pid, int *status=nullptr)
Waits for a specific process to terminate and retrieves its exit status.
bool terminateProcess (pid_t pid, int signal=15)
Sends a signal to a managed process.
bool killProcess (pid_t pid)
Forcefully terminates a process using SIGKILL.
ProcessState getProcessState (pid_t pid)
Queries and updates the current state of a process.
std::vector< pid_t > getAllProcesses () const
Retrieves a list of all managed process IDs.
void waitForAll ()
Waits for all managed processes to terminate.
void terminateAll ()
Terminates all managed processes gracefully, then forcefully if needed.
void printProcessInfo (pid_t pid)
Prints detailed information about a specific process.
void printAllProcesses ()
Prints a summary of all managed processes.
Detailed Description
Definition at line 31 of file ProcessManager.h.
Constructor & Destructor Documentation
ProcessManager()
PTManager::ProcessManager::ProcessManager () default
~ProcessManager()
PTManager::ProcessManager::~ProcessManager ()
Destructor that ensures all managed processes are cleaned up.
Terminates all running processes gracefully (SIGTERM), then forcefully (SIGKILL) if necessary, and waits for them to complete. Prevents zombie processes.
Definition at line 29 of file ProcessManager.cpp.
References terminateAll().
Member Function Documentation
createProcess()
pid_t PTManager::ProcessManager::createProcess (const std::string & name, std::function< int()> task)
Creates a new child process to execute a task.
Parameters
name Human-readable identifier for the process
task Function object containing the code to execute in the child process
Returns
PID of the created child process, or -1 on failure
Uses fork() to create a child process. The child executes the task and exits with the task's return value. The parent records the process metadata and continues execution. The task function should not return to caller - it will be terminated with exit().
Definition at line 45 of file ProcessManager.cpp.
References PTManager::RUNNING, and PTManager::Process::state.
getAllProcesses()
std::vector< pid_t > PTManager::ProcessManager::getAllProcesses () const
Retrieves a list of all managed process IDs.
Returns
Vector containing PIDs of all processes tracked by this manager
Includes both running and terminated processes that haven't been removed from the internal tracking map.
Definition at line 180 of file ProcessManager.cpp.
getProcessState()
ProcessState PTManager::ProcessManager::getProcessState (pid_t pid)
Queries and updates the current state of a process.
Parameters
pid Process ID to check
Returns
Current ProcessState, or TERMINATED if PID not found
Uses non-blocking waitpid() with WNOHANG to check if the process has terminated without blocking. Updates internal state if termination is detected. Does not affect zombie processes - they remain until explicitly waited for.
Definition at line 152 of file ProcessManager.cpp.
References PTManager::RUNNING, and PTManager::TERMINATED.
killProcess()
bool PTManager::ProcessManager::killProcess (pid_t pid)
Forcefully terminates a process using SIGKILL.
Parameters
pid Process ID to kill
Returns
true if SIGKILL was successfully sent, false otherwise
SIGKILL cannot be caught or ignored - guarantees process termination. Use terminateProcess(pid, SIGTERM) for graceful shutdown when possible.
Definition at line 138 of file ProcessManager.cpp.
References terminateProcess().
Referenced by terminateAll().
printAllProcesses()
void PTManager::ProcessManager::printAllProcesses ()
Prints a summary of all managed processes.
Displays total process count followed by detailed information for each process. Useful for debugging and monitoring the state of all child processes.
Definition at line 271 of file ProcessManager.cpp.
References printProcessInfo().
printProcessInfo()
void PTManager::ProcessManager::printProcessInfo (pid_t pid)
Prints detailed information about a specific process.
Parameters
pid Process ID to display information for
Displays PID, name, current state, and exit status (if terminated). Prints "not found" message if the PID is not managed by this ProcessManager.
Definition at line 240 of file ProcessManager.cpp.
References PTManager::BLOCKED, PTManager::CREATED, PTManager::Process::exitStatus, PTManager::Process::name, PTManager::Process::pid, PTManager::READY, PTManager::RUNNING, PTManager::Process::state, and PTManager::TERMINATED.
Referenced by printAllProcesses().
terminateAll()
void PTManager::ProcessManager::terminateAll ()
Terminates all managed processes gracefully, then forcefully if needed.
First attempts graceful termination by sending SIGTERM to all processes, waits 1 second for them to clean up, then sends SIGKILL to any survivors. Finally waits for all processes to be reaped to prevent zombies.
This two-phase approach allows processes to perform cleanup operations before being forcefully killed.
Definition at line 213 of file ProcessManager.cpp.
References killProcess(), PTManager::TERMINATED, terminateProcess(), and waitForAll().
Referenced by ~ProcessManager().
terminateProcess()
bool PTManager::ProcessManager::terminateProcess (pid_t pid, int signal = 15)
Sends a signal to a managed process.
Parameters
pid Process ID to send signal to
signal Signal number (e.g., SIGTERM, SIGKILL, SIGSTOP)
Returns
true if signal was successfully sent, false if process not found or kill() failed
Does not wait for process termination - only sends the signal. The process may ignore or handle certain signals (except SIGKILL and SIGSTOP).
Definition at line 115 of file ProcessManager.cpp.
Referenced by killProcess(), and terminateAll().
waitForAll()
void PTManager::ProcessManager::waitForAll ()
Waits for all managed processes to terminate.
Blocks until every non-terminated process has exited. Skips processes already marked as TERMINATED to avoid waiting on already-reaped processes.
Definition at line 195 of file ProcessManager.cpp.
References PTManager::TERMINATED, and waitForProcess().
Referenced by terminateAll().
waitForProcess()
bool PTManager::ProcessManager::waitForProcess (pid_t pid, int * status = nullptr)
Waits for a specific process to terminate and retrieves its exit status.
Parameters
pid Process ID to wait for
status Optional pointer to store the exit status (can be nullptr)
Returns
true if process was found and successfully waited for, false otherwise
Blocks until the specified process terminates. Updates internal process state and extracts the exit code if the process exited normally. Returns false if the PID is not managed by this ProcessManager.
Definition at line 80 of file ProcessManager.cpp.
References PTManager::TERMINATED.
Referenced by waitForAll().
The documentation for this class was generated from the following files:
include/ProcessManager.h
src/ProcessManager.cpp