var searchData=
[
  ['pattern_0',['Producer-Consumer Pattern',['../index.html#autotoc_md47',1,'']]],
  ['performance_20comparison_1',['IPC Performance Comparison',['../index.html#autotoc_md59',1,'']]],
  ['performance_20considerations_2',['⚡ Performance Considerations',['../index.html#autotoc_md57',1,'']]],
  ['pid_3',['pid',['../classPTManager_1_1Process.html#a574c01abd39f3b8a1faaf5a118f911e7',1,'PTManager::Process']]],
  ['pipe_4',['pipe',['../classPTManager_1_1Pipe.html',1,'PTManager::Pipe'],['../classPTManager_1_1Pipe.html#ae109564c69b363f8cdeebee706c073d4',1,'PTManager::Pipe::Pipe()'],['../classPTManager_1_1Pipe.html#a03e4bd14f6c888284676feda47e338f0',1,'PTManager::Pipe::Pipe(const Pipe &amp;)=delete']]],
  ['pipe_20communication_5',['Example 3: Unnamed Pipe Communication',['../index.html#autotoc_md33',1,'']]],
  ['pool_6',['Thread Pool',['../index.html#autotoc_md5',1,'']]],
  ['pool_20sizing_7',['Thread Pool Sizing',['../index.html#autotoc_md58',1,'']]],
  ['pool_20with_20tasks_8',['Example 2: Thread Pool with Tasks',['../index.html#autotoc_md32',1,'']]],
  ['post_9',['post',['../classPTManager_1_1Semaphore.html#aeaa1e82945578b4d5ffafb57cca4438d',1,'PTManager::Semaphore']]],
  ['practices_10',['Best Practices',['../index.html#autotoc_md56',1,'']]],
  ['prerequisites_11',['📦 Prerequisites',['../index.html#autotoc_md8',1,'']]],
  ['prevention_12',['Example 7: Deadlock Prevention',['../index.html#autotoc_md37',1,'']]],
  ['primitives_13',['primitives',['../index.html#autotoc_md7',1,'Synchronization Primitives'],['../index.html#autotoc_md52',1,'Synchronization Primitives']]],
  ['printallprocesses_14',['printAllProcesses',['../classPTManager_1_1ProcessManager.html#ac2fbcc9509af0b9174885beea87721c0',1,'PTManager::ProcessManager']]],
  ['printprocessinfo_15',['printProcessInfo',['../classPTManager_1_1ProcessManager.html#af2e16186e39a765030bde6c978251e95',1,'PTManager::ProcessManager']]],
  ['printthreadstates_16',['printThreadStates',['../classPTManager_1_1ThreadPool.html#abd4d4e314563fbb768468b5985348501',1,'PTManager::ThreadPool']]],
  ['process_17',['process',['../classPTManager_1_1Process.html',1,'PTManager::Process'],['../classPTManager_1_1Process.html#ad0a72224a27f917e33e6f81176528a53',1,'PTManager::Process::Process()']]],
  ['process_20and_20thread_20management_20library_18',['Process and Thread Management Library',['../index.html',1,'']]],
  ['process_20communication_19',['process communication',['../index.html#autotoc_md28',1,'3. IPC (Inter-Process Communication)'],['../index.html#autotoc_md42',1,'4. Inter-Process Communication']]],
  ['process_20communication_20ipc_20',['Inter-Process Communication (IPC)',['../index.html#autotoc_md6',1,'']]],
  ['process_20management_21',['process management',['../index.html#autotoc_md39',1,'1. Process Management'],['../index.html#autotoc_md4',1,'Process Management']]],
  ['processes_22',['Example 1: Create and Manage Processes',['../index.html#autotoc_md31',1,'']]],
  ['processmanager_23',['processmanager',['../index.html#autotoc_md26',1,'1. ProcessManager'],['../classPTManager_1_1ProcessManager.html#ab5515b862dbd94b4317e6e17c19ac88f',1,'PTManager::ProcessManager::ProcessManager()'],['../index.html#autotoc_md49',1,'ProcessManager'],['../classPTManager_1_1ProcessManager.html',1,'PTManager::ProcessManager']]],
  ['processmanager_2ecpp_24',['ProcessManager.cpp',['../ProcessManager_8cpp.html',1,'']]],
  ['processmanager_2eh_25',['ProcessManager.h',['../ProcessManager_8h.html',1,'']]],
  ['processstate_26',['ProcessState',['../namespacePTManager.html#a874d5aaafbe35905f1ae5754b3fc7238',1,'PTManager']]],
  ['processthreadmanager_27',['About ProcessThreadManager',['../md_ABOUT.html',1,'']]],
  ['producer_20consumer_20pattern_28',['Producer-Consumer Pattern',['../index.html#autotoc_md47',1,'']]],
  ['producer_20consumer_20with_20semaphore_29',['Example 5: Producer-Consumer with Semaphore',['../index.html#autotoc_md35',1,'']]],
  ['project_20information_30',['Project Information',['../md_ABOUT.html#autotoc_md81',1,'']]],
  ['project_20structure_31',['project structure',['../index.html#autotoc_md17',1,'🏗️ Project Structure'],['../index.html#autotoc_md15',1,'1. Clone or Create Project Structure']]],
  ['ptmanager_32',['PTManager',['../namespacePTManager.html',1,'']]]
];
