ProcessThreadManager: PTManager::SharedMemory Class Reference
PTManager::SharedMemory Class Reference
#include <IPC.h>
Public Member Functions
SharedMemory (const std::string &shmName, size_t shmSize)
Constructs a shared memory object wrapper.
~SharedMemory ()
Destructor that ensures complete cleanup of shared memory resources.
bool create (mode_t mode=0666)
Creates a new shared memory object.
bool open ()
Opens an existing shared memory object.
bool map (int prot=3)
Maps the shared memory into the process address space.
void unmap ()
Unmaps the shared memory from the process address space.
void close ()
Closes the file descriptor.
bool unlink ()
Removes the shared memory object from the system.
void * getAddress () const
size_t getSize () const
bool writeData (const void *data, size_t dataSize, size_t offset=0)
Writes data to the shared memory region.
bool readData (void *buffer, size_t dataSize, size_t offset=0)
Reads data from the shared memory region.
template<typename T >
T * getAs ()
Detailed Description
Definition at line 65 of file IPC.h.
Constructor & Destructor Documentation
SharedMemory()
PTManager::SharedMemory::SharedMemory (const std::string & shmName, size_t shmSize)
Constructs a shared memory object wrapper.
Parameters
shmName Name of the shared memory object (must start with '/')
shmSize Size of the shared memory region in bytes
Initializes the object but does not create or map the shared memory. Call create() or open(), then map() to use the shared memory.
Definition at line 325 of file IPC.cpp.
~SharedMemory()
PTManager::SharedMemory::~SharedMemory ()
Destructor that ensures complete cleanup of shared memory resources.
Unmaps the memory region, closes the file descriptor, and unlinks the shared memory object if this instance created it.
Definition at line 335 of file IPC.cpp.
References close(), unlink(), and unmap().
Member Function Documentation
close()
void PTManager::SharedMemory::close ()
Closes the file descriptor.
Does not unmap or unlink the shared memory. Safe to call multiple times.
Definition at line 435 of file IPC.cpp.
References close().
Referenced by ~SharedMemory(), close(), and create().
create()
bool PTManager::SharedMemory::create (mode_t mode = 0666)
Creates a new shared memory object.
Parameters
mode Permission bits (e.g., 0666)
Returns
true if successfully created and sized, false otherwise
Creates the shared memory object using shm_open() and sets its size using ftruncate(). Both operations must succeed for the method to return true. Cleans up file descriptor on ftruncate() failure.
Definition at line 353 of file IPC.cpp.
References close().
getAddress()
void * PTManager::SharedMemory::getAddress () const inline
Definition at line 85 of file IPC.h.
getAs()
template<typename T > T * PTManager::SharedMemory::getAs () inline
Definition at line 93 of file IPC.h.
getSize()
size_t PTManager::SharedMemory::getSize () const inline
Definition at line 86 of file IPC.h.
map()
bool PTManager::SharedMemory::map (int prot = 3)
Maps the shared memory into the process address space.
Parameters
prot Protection flags (e.g., PROT_READ | PROT_WRITE)
Returns
true if successfully mapped, false otherwise
Uses mmap() to make the shared memory accessible as a regular memory region. Must be called after create() or open().
Definition at line 400 of file IPC.cpp.
open()
bool PTManager::SharedMemory::open ()
Opens an existing shared memory object.
Returns
true if successfully opened, false otherwise
Opens the shared memory object with read-write permissions. The object must already exist (created by another process).
Definition at line 380 of file IPC.cpp.
readData()
bool PTManager::SharedMemory::readData (void * buffer, size_t dataSize, size_t offset = 0)
Reads data from the shared memory region.
Parameters
buffer Pointer to destination buffer
dataSize Number of bytes to read
offset Offset within the shared memory region
Returns
true if read successful, false if not mapped or out of bounds
Validates that the read operation stays within bounds. Uses memcpy for the actual data transfer.
Definition at line 487 of file IPC.cpp.
unlink()
bool PTManager::SharedMemory::unlink ()
Removes the shared memory object from the system.
Returns
true if successfully unlinked, false otherwise
Destroys the shared memory object. Should only be called by the creating process. Other processes with existing mappings can continue using them until unmapped.
Definition at line 450 of file IPC.cpp.
Referenced by ~SharedMemory().
unmap()
void PTManager::SharedMemory::unmap ()
Unmaps the shared memory from the process address space.
Releases the memory mapping but does not destroy the shared memory object. Other processes can still access it.
Definition at line 421 of file IPC.cpp.
Referenced by ~SharedMemory().
writeData()
bool PTManager::SharedMemory::writeData (const void * data, size_t dataSize, size_t offset = 0)
Writes data to the shared memory region.
Parameters
data Pointer to source data
dataSize Number of bytes to write
offset Offset within the shared memory region
Returns
true if write successful, false if not mapped or out of bounds
Validates that the write operation stays within bounds. Uses memcpy for the actual data transfer.
Definition at line 469 of file IPC.cpp.
The documentation for this class was generated from the following files:
include/IPC.h
src/IPC.cpp