ProcessThreadManager: PTManager::ThreadPool Class Reference
PTManager::ThreadPool Class Reference
#include <ThreadPool.h>
Public Member Functions
ThreadPool (size_t numThreads)
Constructs a thread pool with specified number of worker threads.
~ThreadPool ()
Destructor that ensures graceful shutdown of the thread pool.
ThreadPool (const ThreadPool &)=delete
ThreadPool & operator= (const ThreadPool &)=delete
template<typename F , typename... Args>
auto enqueue (F &&f, Args &&... args) -> std::future< std::result_of_t< F(Args...)> >
size_t getPoolSize () const
size_t getActiveTasks () const
size_t getQueuedTasks ()
Returns the number of tasks waiting in the queue.
void waitForCompletion ()
Blocks until all queued and active tasks complete.
void shutdown ()
Gracefully shuts down the thread pool.
ThreadState getThreadState (size_t id)
Queries the current state of a specific worker thread.
void printThreadStates ()
Prints a comprehensive status report of the thread pool.
Detailed Description
Definition at line 23 of file ThreadPool.h.
Constructor & Destructor Documentation
ThreadPool() [1/2]
PTManager::ThreadPool::ThreadPool (size_t numThreads) explicit
Constructs a thread pool with specified number of worker threads.
Parameters
numThreads Number of worker threads to create in the pool
Initializes all worker threads in IDLE state and starts them immediately. Each worker runs the workerThread() function, waiting for tasks to be enqueued. Workers persist until shutdown() is called.
Definition at line 15 of file ThreadPool.cpp.
References PTManager::IDLE.
~ThreadPool()
PTManager::ThreadPool::~ThreadPool ()
Destructor that ensures graceful shutdown of the thread pool.
Calls shutdown() to stop all workers and wait for them to finish. Ensures no thread handles are left dangling and all resources are cleaned up.
Definition at line 33 of file ThreadPool.cpp.
References shutdown().
ThreadPool() [2/2]
PTManager::ThreadPool::ThreadPool (const ThreadPool &) delete
Member Function Documentation
enqueue()
template<typename F , typename... Args> auto PTManager::ThreadPool::enqueue (F && f, Args &&... args) -> std::future<std::result_of_t<F(Args...)>>
Definition at line 66 of file ThreadPool.h.
getActiveTasks()
size_t PTManager::ThreadPool::getActiveTasks () const inline
Definition at line 53 of file ThreadPool.h.
getPoolSize()
size_t PTManager::ThreadPool::getPoolSize () const inline
Definition at line 52 of file ThreadPool.h.
getQueuedTasks()
size_t PTManager::ThreadPool::getQueuedTasks ()
Returns the number of tasks waiting in the queue.
Returns
Number of pending tasks not yet assigned to workers
Thread-safe query of the task queue size. Does not include tasks currently being executed by workers.
Definition at line 103 of file ThreadPool.cpp.
Referenced by printThreadStates().
getThreadState()
ThreadState PTManager::ThreadPool::getThreadState (size_t id)
Queries the current state of a specific worker thread.
Parameters
id Thread identifier (0-based index)
Returns
Current ThreadState, or TERMINATED if id is invalid
Thread-safe query of worker state. States are updated by the worker itself: IDLE while waiting, RUNNING while executing a task, TERMINATED after shutdown.
Definition at line 164 of file ThreadPool.cpp.
References PTManager::TERMINATED.
operator=()
ThreadPool & PTManager::ThreadPool::operator= (const ThreadPool &) delete
printThreadStates()
void PTManager::ThreadPool::printThreadStates ()
Prints a comprehensive status report of the thread pool.
Displays pool size, active task count, queued task count, and the state of each individual worker thread. Thread-safe snapshot of current state. Useful for debugging and monitoring thread pool health and utilization.
Definition at line 180 of file ThreadPool.cpp.
References PTManager::BLOCKED, getQueuedTasks(), PTManager::IDLE, PTManager::RUNNING, and PTManager::TERMINATED.
shutdown()
void PTManager::ThreadPool::shutdown ()
Gracefully shuts down the thread pool.
Sets the stop flag, wakes all waiting workers, and joins all threads. Workers will complete their current tasks but won't pick up new ones. Remaining queued tasks are discarded. Safe to call multiple times. After shutdown, the thread pool cannot be restarted.
Definition at line 135 of file ThreadPool.cpp.
Referenced by ~ThreadPool().
waitForCompletion()
void PTManager::ThreadPool::waitForCompletion ()
Blocks until all queued and active tasks complete.
Polls the queue and active task count every 10ms until both are zero. Does not prevent new tasks from being enqueued during the wait. Useful for synchronization points where all work must finish before proceeding.
Definition at line 115 of file ThreadPool.cpp.
The documentation for this class was generated from the following files:
include/ThreadPool.h
src/ThreadPool.cpp