ProcessThreadManager: PTManager::NamedPipe Class Reference
PTManager::NamedPipe Class Reference
#include <IPC.h>
Public Member Functions
NamedPipe (const std::string &pipePath)
Constructs a named pipe (FIFO) wrapper.
~NamedPipe ()
Destructor that ensures cleanup of named pipe resources.
bool create (mode_t mode=0666)
Creates the named pipe (FIFO) in the filesystem.
bool openForReading ()
Opens the named pipe for reading.
bool openForWriting ()
Opens the named pipe for writing.
void close ()
Closes the file descriptor.
bool remove ()
Removes the named pipe from the filesystem.
ssize_t write (const void *data, size_t size)
Writes raw binary data to the named pipe.
ssize_t read (void *buffer, size_t size)
Reads raw binary data from the named pipe.
bool writeString (const std::string &str)
Writes a string with length-prefixed protocol.
std::string readString (size_t maxSize=4096)
Reads a length-prefixed string from the named pipe.
Detailed Description
Definition at line 41 of file IPC.h.
Constructor & Destructor Documentation
NamedPipe()
PTManager::NamedPipe::NamedPipe (const std::string & pipePath)
Constructs a named pipe (FIFO) wrapper.
Parameters
pipePath Filesystem path where the FIFO will be created
Initializes the object but does not create the actual FIFO. Call create() to establish the named pipe in the filesystem.
Definition at line 151 of file IPC.cpp.
~NamedPipe()
PTManager::NamedPipe::~NamedPipe ()
Destructor that ensures cleanup of named pipe resources.
Closes the file descriptor and removes the FIFO from the filesystem if this instance created it (prevents premature removal by readers/writers).
Definition at line 160 of file IPC.cpp.
References close(), and remove().
Member Function Documentation
close()
void PTManager::NamedPipe::close ()
Closes the file descriptor.
Does not remove the FIFO from the filesystem. Safe to call multiple times.
Definition at line 232 of file IPC.cpp.
References close().
Referenced by ~NamedPipe(), and close().
create()
bool PTManager::NamedPipe::create (mode_t mode = 0666)
Creates the named pipe (FIFO) in the filesystem.
Parameters
mode Permission bits for the FIFO (e.g., 0666)
Returns
true if created or already exists, false on error
Uses mkfifo() to create a special file in the filesystem that acts as a pipe. Handles EEXIST gracefully by treating existing FIFOs as success.
Definition at line 176 of file IPC.cpp.
openForReading()
bool PTManager::NamedPipe::openForReading ()
Opens the named pipe for reading.
Returns
true if successfully opened, false otherwise
Blocks until a writer opens the other end of the pipe. This is standard FIFO behavior per POSIX specifications.
Definition at line 200 of file IPC.cpp.
openForWriting()
bool PTManager::NamedPipe::openForWriting ()
Opens the named pipe for writing.
Returns
true if successfully opened, false otherwise
Blocks until a reader opens the other end of the pipe. This is standard FIFO behavior per POSIX specifications.
Definition at line 217 of file IPC.cpp.
read()
ssize_t PTManager::NamedPipe::read (void * buffer, size_t size)
Reads raw binary data from the named pipe.
Parameters
buffer Pointer to the destination buffer
size Maximum number of bytes to read
Returns
Number of bytes read, or -1 if pipe not open
Definition at line 274 of file IPC.cpp.
Referenced by readString().
readString()
std::string PTManager::NamedPipe::readString (size_t maxSize = 4096)
Reads a length-prefixed string from the named pipe.
Parameters
maxSize Maximum allowed string length for safety
Returns
The read string, or empty string on error
Protocol: Reads length first, then content. Enforces maxSize limit to prevent memory exhaustion.
Definition at line 302 of file IPC.cpp.
References read().
remove()
bool PTManager::NamedPipe::remove ()
Removes the named pipe from the filesystem.
Returns
true if successfully removed, false otherwise
Uses unlink() to delete the FIFO special file. Should only be called by the process that created the FIFO.
Definition at line 247 of file IPC.cpp.
Referenced by ~NamedPipe().
write()
ssize_t PTManager::NamedPipe::write (const void * data, size_t size)
Writes raw binary data to the named pipe.
Parameters
data Pointer to the data buffer
size Number of bytes to write
Returns
Number of bytes written, or -1 if pipe not open
Definition at line 262 of file IPC.cpp.
Referenced by writeString().
writeString()
bool PTManager::NamedPipe::writeString (const std::string & str)
Writes a string with length-prefixed protocol.
Parameters
str The string to write
Returns
true if entire string was written successfully, false otherwise
Protocol: Writes length first (size_t), then string content.
Definition at line 287 of file IPC.cpp.
References write().
The documentation for this class was generated from the following files:
include/IPC.h
src/IPC.cpp