ProcessThreadManager: PTManager::Pipe Class Reference
PTManager::Pipe Class Reference
#include <IPC.h>
Public Member Functions
Pipe ()
Constructs an anonymous pipe for inter-process communication.
~Pipe ()
Destructor that ensures proper cleanup of pipe resources.
Pipe (const Pipe &)=delete
Pipe & operator= (const Pipe &)=delete
int getReadFd () const
int getWriteFd () const
void closeRead ()
Closes the read end of the pipe.
void closeWrite ()
Closes the write end of the pipe.
void close ()
Closes both ends of the pipe and marks it as closed.
ssize_t write (const void *data, size_t size)
Writes raw binary data to the pipe.
ssize_t read (void *buffer, size_t size)
Reads raw binary data from the pipe.
bool writeString (const std::string &str)
Writes a string with length-prefixed protocol.
std::string readString (size_t maxSize=4096)
Reads a length-prefixed string from the pipe.
Detailed Description
Definition at line 12 of file IPC.h.
Constructor & Destructor Documentation
Pipe() [1/2]
PTManager::Pipe::Pipe ()
Constructs an anonymous pipe for inter-process communication.
Creates a unidirectional communication channel using the pipe() system call. The pipe consists of two file descriptors: fds[0] for reading and fds[1] for writing. Logs error to stderr if pipe creation fails.
Definition at line 21 of file IPC.cpp.
~Pipe()
PTManager::Pipe::~Pipe ()
Destructor that ensures proper cleanup of pipe resources.
Automatically closes both ends of the pipe to prevent file descriptor leaks.
Definition at line 34 of file IPC.cpp.
References close().
Pipe() [2/2]
PTManager::Pipe::Pipe (const Pipe &) delete
Member Function Documentation
close()
void PTManager::Pipe::close ()
Closes both ends of the pipe and marks it as closed.
Ensures complete cleanup of pipe resources. Sets isOpen to false to prevent operations on a closed pipe.
Definition at line 70 of file IPC.cpp.
References closeRead(), and closeWrite().
Referenced by ~Pipe(), closeRead(), and closeWrite().
closeRead()
void PTManager::Pipe::closeRead ()
Closes the read end of the pipe.
Invalidates the read file descriptor and prevents further read operations. Safe to call multiple times or on already-closed descriptors.
Definition at line 44 of file IPC.cpp.
References close().
Referenced by close().
closeWrite()
void PTManager::Pipe::closeWrite ()
Closes the write end of the pipe.
Invalidates the write file descriptor and prevents further write operations. Safe to call multiple times or on already-closed descriptors.
Definition at line 57 of file IPC.cpp.
References close().
Referenced by close().
getReadFd()
int PTManager::Pipe::getReadFd () const inline
Definition at line 25 of file IPC.h.
getWriteFd()
int PTManager::Pipe::getWriteFd () const inline
Definition at line 26 of file IPC.h.
operator=()
Pipe & PTManager::Pipe::operator= (const Pipe &) delete
read()
ssize_t PTManager::Pipe::read (void * buffer, size_t size)
Reads raw binary data from the pipe.
Parameters
buffer Pointer to the buffer where data will be stored
size Maximum number of bytes to read
Returns
Number of bytes read, or -1 on error
Note
Returns -1 if pipe is closed or read end is invalid
Definition at line 99 of file IPC.cpp.
Referenced by readString().
readString()
std::string PTManager::Pipe::readString (size_t maxSize = 4096)
Reads a length-prefixed string from the pipe.
Parameters
maxSize Maximum allowed string length for safety
Returns
The read string, or empty string on error
Protocol: First reads the length, then reads that many bytes. Enforces maxSize limit to prevent memory exhaustion attacks. Allocates buffer with extra byte for null terminator.
Definition at line 129 of file IPC.cpp.
References read().
write()
ssize_t PTManager::Pipe::write (const void * data, size_t size)
Writes raw binary data to the pipe.
Parameters
data Pointer to the data buffer to write
size Number of bytes to write
Returns
Number of bytes written, or -1 on error
Note
Returns -1 if pipe is closed or write end is invalid
Definition at line 85 of file IPC.cpp.
Referenced by writeString().
writeString()
bool PTManager::Pipe::writeString (const std::string & str)
Writes a string with length-prefixed protocol.
Parameters
str The string to write
Returns
true if entire string was written successfully, false otherwise
Protocol: First writes the length as size_t, then writes the string content. This allows the receiver to know exactly how many bytes to read.
Definition at line 113 of file IPC.cpp.
References write().
The documentation for this class was generated from the following files:
include/IPC.h
src/IPC.cpp