ProcessThreadManager: PTManager::SafeMutex Class Reference
PTManager::SafeMutex Class Reference
#include <Synchronization.h>
Public Member Functions
SafeMutex (const std::string &mutexName="")
Constructs a SafeMutex with deadlock detection capabilities.
bool lock (std::chrono::milliseconds timeout=std::chrono::milliseconds(5000))
Attempts to acquire the mutex with timeout and recursive lock detection.
bool tryLock ()
Attempts to acquire the mutex without blocking.
void unlock ()
Releases the mutex.
std::string getName () const
bool isLocked () const
Checks if the mutex is currently locked.
std::thread::id getOwner () const
Detailed Description
Definition at line 17 of file Synchronization.h.
Constructor & Destructor Documentation
SafeMutex()
PTManager::SafeMutex::SafeMutex (const std::string & mutexName = "") explicit
Constructs a SafeMutex with deadlock detection capabilities.
Parameters
mutexName Identifier for debugging and error messages (defaults to "unnamed")
Initializes the mutex with no owner and zero lock count. The name helps identify which mutex is involved in deadlock situations.
Definition at line 16 of file Synchronization.cpp.
Member Function Documentation
getName()
std::string PTManager::SafeMutex::getName () const inline
Definition at line 31 of file Synchronization.h.
Referenced by PTManager::SafeLockGuard::SafeLockGuard().
getOwner()
std::thread::id PTManager::SafeMutex::getOwner () const inline
Definition at line 33 of file Synchronization.h.
isLocked()
bool PTManager::SafeMutex::isLocked () const
Checks if the mutex is currently locked.
Returns
true if any thread owns the lock, false otherwise
Thread-safe query that checks if owner is set to a valid thread ID.
Definition at line 89 of file Synchronization.cpp.
lock()
bool PTManager::SafeMutex::lock (std::chrono::milliseconds timeout = std::chrono::milliseconds(5000))
Attempts to acquire the mutex with timeout and recursive lock detection.
Parameters
timeout Maximum time to wait for the lock
Returns
true if lock was acquired, false on timeout or recursive lock attempt
Detects and prevents recursive locking by the same thread, which would cause deadlock. Uses timed locking to detect potential deadlocks when timeout expires. Updates owner thread ID and increments lock count on successful acquisition.
Definition at line 30 of file Synchronization.cpp.
Referenced by PTManager::SafeLockGuard::SafeLockGuard().
tryLock()
bool PTManager::SafeMutex::tryLock ()
Attempts to acquire the mutex without blocking.
Returns
true if lock was acquired, false if already locked
Non-blocking lock attempt. Returns immediately regardless of lock availability. Updates owner and lock count on success.
Definition at line 59 of file Synchronization.cpp.
unlock()
void PTManager::SafeMutex::unlock ()
Releases the mutex.
Clears the owner thread ID, decrements lock count, and unlocks the underlying mutex. Caller must ensure they own the lock before calling.
Definition at line 76 of file Synchronization.cpp.
Referenced by PTManager::SafeLockGuard::~SafeLockGuard().
The documentation for this class was generated from the following files:
include/Synchronization.h
src/Synchronization.cpp