ProcessThreadManager: PTManager::SafeLockGuard Class Reference
PTManager::SafeLockGuard Class Reference
#include <Synchronization.h>
Public Member Functions
SafeLockGuard (SafeMutex &m)
RAII wrapper that acquires a SafeMutex and automatically releases it.
~SafeLockGuard ()
Destructor that releases the mutex if it was successfully locked.
SafeLockGuard (const SafeLockGuard &)=delete
SafeLockGuard & operator= (const SafeLockGuard &)=delete
Detailed Description
Definition at line 37 of file Synchronization.h.
Constructor & Destructor Documentation
SafeLockGuard() [1/2]
PTManager::SafeLockGuard::SafeLockGuard (SafeMutex & m) explicit
RAII wrapper that acquires a SafeMutex and automatically releases it.
Parameters
m The SafeMutex to lock
Exceptions
std::runtime_error if lock acquisition fails
Acquires the mutex in the constructor using the default timeout. Throws exception if lock cannot be acquired, preventing silent failures. Ensures the lock is always released when the guard goes out of scope.
Definition at line 105 of file Synchronization.cpp.
References PTManager::SafeMutex::getName(), and PTManager::SafeMutex::lock().
~SafeLockGuard()
PTManager::SafeLockGuard::~SafeLockGuard ()
Destructor that releases the mutex if it was successfully locked.
Automatically unlocks the mutex when the guard goes out of scope. Only unlocks if the lock was successfully acquired in the constructor.
Definition at line 118 of file Synchronization.cpp.
References PTManager::SafeMutex::unlock().
SafeLockGuard() [2/2]
PTManager::SafeLockGuard::SafeLockGuard (const SafeLockGuard &) delete
Member Function Documentation
operator=()
SafeLockGuard & PTManager::SafeLockGuard::operator= (const SafeLockGuard &) delete
The documentation for this class was generated from the following files:
include/Synchronization.h
src/Synchronization.cpp